### PR TITLE
New branding for the project

### PR DESCRIPTION
**Pull request by atraest**
New logo, banner and icons. Also a smaller logo for the README.md. 

These new icons works on both dark and light backgrounds, the old ones unfortunately does not.

### CODE REVIEW

**Comment by antony-jr** [comment]
@cristianovitorino Thank you, I really don't know design that much.

**Comment by atraest** [comment]
> @cristianovitorino Thank you, I really don't know design that much.

No problem, glad to help! I use Blue Glow daily now : ) Can't wait to see the updates on the next release.

**Comment by antony-jr** [comment]
> No problem, glad to help! I use Blue Glow daily now : ) Can't wait to see the updates on the next release.

I'm working on it right now, The problem is the banner, I think I might have to use native labels instead of a png.

**EDIT**: I would also make sure to include your name in the about window.

**Comment by atraest** [comment]
> I'm working on it right now, The problem is the banner, I think I might have to use native labels instead of a png.

I see. Feel free to let me know if you need changes in the design, new formats, access to image sources, etc.

> **EDIT**: I would also make sure to include your name in the about window.

Thanks!

**Pull request merged**
